# workflow yaml code
name: Push Docker Image to Docker Hub             # workflow 이름 지정
on:                                               # 동작 조건 지정
  push:                                           # branch, tags가 push되면 동작하도록
    branches:                                     # **(all branch), - master 만 사용
      - 'master'
    tags:
      - '**'
jobs:                                             # 작업 지정
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout                            # runner에 저장소 코드를 다운로드 후 특정 브랜치로 checkout
        uses: actions/checkout@v2
      
      - name: Docker meta                         # step 이름은 사용자 정의
        id: docker_meta                           # 변수값으로 하위 코드에서 output으로 사용 가능
        uses: crazy-max/ghaction-docker-meta@v1   # 사용할 동작
        with:                                     # 동작에 대한 input값 사용 선언
          images: chaecker/nodejs-ci              # 사용할 docker repository (계정/저장소)
          tag-semver: |                           # 태그로 사용할 버전 정보
            {{version}}
            {{major}}.{{minor}}
      
      # QEMU는 오픈소스 하이퍼 바이저: 다른 플랫폼에서 동작하는 애플리케이션 실행을 위한 에뮬레이터로 사용
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      
      # Buildx는 Docker 19.03 버전부터 기본으로 제공. 다른 플랫폼용으로 빌드할 수 있는 기능 포함
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true                                          # 빌드 후 배포 여부 확인
          tags: ${{ steps.docker_meta.outputs.tags }}         # 빌드 시 위에서 지정한 태그 사용
          labels: ${{ steps.docker_meta.outputs.labels }}     # 빌드 시 위에서 지정한 라벨 사용 
